### ISSUE TITLE
Crash at start - GM Version: 2022.3.0.625

### ISSUE THREAD

**Issue by Madirex** [LAGameStudio/InputCandy#1] opened 2022-04-23 17:21 UTC
Push :: Execution Error - Variable Index [0] out of range [0] - -9.settings(100060,0)
 at gml_Script_anon____struct___274_New_InputCandy_Private_gml_GlobalScript_InputCandy_165580____struct___274_New_InputCandy_Private_gml_GlobalScript_InputCandy (line 2805) -                      if ( !__ICI.Is_Valid_Setting(__INPUTCANDY.setup.settings[i]) ) {
############################################################################################
gml_Script_anon____struct___274_New_InputCandy_Private_gml_GlobalScript_InputCandy_165580____struct___274_New_InputCandy_Private_gml_GlobalScript_InputCandy (line 2805)
gml_Script_anon____struct___274_New_InputCandy_Private_gml_GlobalScript_InputCandy_83089____struct___274_New_InputCandy_Private_gml_GlobalScript_InputCandy (line 1401) -                             __ICI.ActivateSetup();
gml_Script_anon____struct___268_New_InputCandy_gml_GlobalScript_InputCandy_57649____struct___268_New_InputCandy_gml_GlobalScript_InputCandy (line 847) -               Step: function () { __ICI.Step(); },
gml_Object_o_InputCandy_Step_0 (line 3) - __IC.Step();

**Comment by h3rb** [comment] 2022-05-07 04:54
Thanks for reporting this.  It is only by luck that I too ran into the issue today, but I'm glad I could address this unintended issue.

I believe this occurs when no gamepads are connected, and the player only has a keyboard and mouse.

I think this was fixed in my latest push.  If you would, please verify by doing a code review (git pull to update and see if the issue is fixed).

I also fixed some bugs that were related, and I didn't see any new issues but I could be missing something.  Please try to use the configuration features as intended, and we'll see if there are any other missed checks for "none" when device or empty settings variables are referenced.

**Comment by Madirex** [comment] 2022-05-16 21:15
The problem keeps happening. I tried to connect a gamepad but I still get an error:

`############################################################################################
ERROR in
action number 1
of  Step Event0
for object o_InputCandy:

Push :: Execution Error - Variable Index [0] out of range [0] - -9.settings(100060,0)
 at gml_Script_anon____struct___274_New_InputCandy_Private_gml_GlobalScript_InputCandy_165670____struct___274_New_InputCandy_Private_gml_GlobalScript_InputCandy (line 2807) -                      if ( !__ICI.Is_Valid_Setting(__INPUTCANDY.setup.settings[i]) ) {
############################################################################################
gml_Script_anon____struct___274_New_InputCandy_Private_gml_GlobalScript_InputCandy_165670____struct___274_New_InputCandy_Private_gml_GlobalScript_InputCandy (line 2807)
gml_Script_anon____struct___274_New_InputCandy_Private_gml_GlobalScript_InputCandy_83089____struct___274_New_InputCandy_Private_gml_GlobalScript_InputCandy (line 1401) -                             __ICI.ActivateSetup();
gml_Script_anon____struct___268_New_InputCandy_gml_GlobalScript_InputCandy_57649____struct___268_New_InputCandy_gml_GlobalScript_InputCandy (line 847) -               Step: function () { __ICI.Step(); },
gml_Object_o_InputCandy_Step_0 (line 3) - __IC.Step();
`

**Comment by h3rb** [comment] 2022-05-31 20:32
Did you update from the repo?  https://github.com/LAGameStudio/InputCandy/releases/tag/0.9.92

**Comment by Madirex** [comment] 2022-05-31 20:37
Yes

**Comment by h3rb** [comment] 2022-06-07 05:00
So, on my Windows PC, I just started up InputCandy in **Runtime 2022.5.0.8** ... I clicked the logo until I saw "Diagnostics" ... I had no controllers plugged in.  I plugged in a "Pirahna xtreme" (it's a retrolink n64-style controller) .. Now I see "active devices #0 Piranha" and no crashes.  I clicked the logo until it said "SIMPLE MODE" in the upper left.  I unplugged... Now I see it disappear from the list.  

You said: "The problem keeps happening. I tried to connect a gamepad but I still get an error:"

I need more information.


According to your report, the "ERROR in action number 1 of Step Event0 for object o_InputCandy" appears to happen at InputCandy Line 2807.  If I open up the Scripts > InputCandy > InputCandy script, and visit line 2807, it indeed does look like the one you it shows in the above execution error.  ("- if ( !__ICI.Is_Valid_Setting(__INPUTCANDY.setup.settings[i]) ) {") .. since it is indicating 0 is out of range, this tand it says -9.settings, -9 is actually indicating that the structure __INPUTCANDY.setup isn't there, or the array __INPUTCANDY.setup.settings isn't there, ie Inputcandy has not been initialized.

Questions:
1) Are you using the test application when you see this bug, or your own game where you have attempted to use InputCandy to integrate into another project?
2) Are you doing this on a Windows PC, Ubuntu Linux, mobile/tablet or MacOS?  
3) What kind of controller are you using? 
4)  Is it plugged in when you start the test app?  
5)  Or are you plugging it in after and where/when/what panel are you plugging it in during?

**Comment by h3rb** [comment] 2022-06-07 05:17
Aha!  It's the settings files.  when I moved my files out of AppData it caused the same crash.  let me see...

**Comment by h3rb** [comment] 2022-06-07 05:33
https://github.com/LAGameStudio/InputCandy/releases/tag/0.9.93 should fix that.. let me know if you run into anything else and please let me know if it does indeed fix your issue

**Comment by Madirex** [comment] 2022-06-15 09:34
Yes, it has been fixed! Good job!

Before it crashed as soon as you open it, now it doesn't.

However, when I was testing the extension a bit, I realized that when a player is spawned, you go back to the controls screen and hit the arrow button to go back, it crashes again with a different error:

_cannot find instance INPUYCANDY.players[i].data.scored:_

**Video:** https://www.youtube.com/watch?v=ruWcldizHZg

Sorry for the late reply, I've been very busy lately

**Closed as completed** 2023-07-11 02:19 UTC
Labels: bug, believed fixed
